"""empty message

Revision ID: 35ca187da413
Revises: 
Create Date: 2024-11-15 17:33:43.112551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ca187da413'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fystboll',
    sa.Column('pallet', sa.String(length=10), nullable=False),
    sa.Column('item_code', sa.String(length=10), nullable=False),
    sa.Column('item_description', sa.String(length=50), nullable=False),
    sa.Column('width', sa.String(length=10), nullable=False),
    sa.Column('length', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.String(length=10), nullable=False),
    sa.Column('coil', sa.String(length=10), nullable=False),
    sa.Column('customer', sa.String(length=10), nullable=False),
    sa.Column('customer_firm_name', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=12), nullable=False),
    sa.Column('doc_number', sa.String(length=15), nullable=False),
    sa.Column('ord_number', sa.String(length=10), nullable=False),
    sa.Column('ord_date', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('coil')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('fystboll')
    # ### end Alembic commands ###
